package com.uttec.views.util;

public class Genre {

	/**
	 * Used for fast implementation, can be removed
	 * 
	 */
	public static String[] GENRES = { "ACAPELLA", "ACID", "ACID JAZZ", "ACID PUNK", "ACOUSTIC", "ALTERNROCK",
			"ALTERNATIVE", "AMBIENT", "AVANTGARDE", "BALLAD", "BASS", "BEBOB", "BIG BAND", "BLUEGRASS", "BLUES",
			"BOOTY BASS", "CABARET", "CELTIC", "CHAMBER MUSIC", "CHANSON", "CHORUS", "CHRISTIAN RAP", "CLASSIC ROCK",
			"CLASSICAL", "CLUB", "COMEDY", "COUNTRY", "CULT", "DANCE", "DANCE HALL", "DARKWAVE", "DEATH METAL", "DISCO",
			"DREAM", "DRUM SOLO", "DUET", "EASY LISTENING", "ELECTRONIC", "ETHNIC", "EURO-HOUSE", "EURO-TECHNO",
			"EURODANCE", "FAST FUSION", "FOLK", "FOLK-ROCK", "FOLKLORE", "FREESTYLE", "FUNK", "FUSION", "GAME",
			"GANGSTA", "GOSPEL", "GOTHIC", "GOTHIC ROCK", "GRUNGE", "HARD ROCK", "HIP-HOP", "HOUSE", "HUMOUR",
			"INDUSTRIAL", "INSTRUMENTAL", "INSTRUMENTAL POP", "INSTRUMENTAL ROCK", "JAZZ", "JAZZ+FUNK", "JUNGLE",
			"LATIN", "LO-FI", "MEDITATIVE", "METAL", "MUSICAL", "NATIONAL FOLK", "NATIVE AMERICAN", "NEW AGE",
			"NEW WAVE", "NOISE", "OLDIES", "OPERA", "OTHER", "POLKA", "POP", "POP-FOLK", "POP/FUNK", "PORN GROOVE",
			"POWER BALLAD", "PRANKS", "PRIMUS", "PROGRESSIVE ROCK", "PSYCHADELIC", "PSYCHEDELIC ROCK", "PUNK",
			"PUNK ROCK", "R&B", "RAP", "RAVE", "REGGAE", "RETRO", "REVIVAL", "RHYTHMIC SOUL", "ROCK", "ROCK & ROLL",
			"SAMBA", "SATIRE", "SHOWTUNES", "SKA", "SLOW JAM", "SLOW ROCK", "SONATA", "SOUL", "SOUND CLIP",
			"SOUNDTRACK", "SOUTHERN ROCK", "SPACE", "SPEECH", "SWING", "SYMPHONIC ROCK", "SYMPHONY", "TANGO", "TECHNO",
			"TECHNO-INDUSTRIAL", "TOP 40", "TRAILER", "TRANCE", "TRIBAL", "TRIP-HOP", "VOCAL" };

}
